### ISSUE TITLE
dataset split

### ISSUE THREAD

**Issue by zjy6Archer** [hshanbha/contactless-mat-id#1]
Hello, I would like to know the detailed way of dividing your data set here, which is the following:

1. Divide frames: Collect different frame data obtained from different objects, use part of the frame for training, and the other part of the frame data for verifying and testing.

2. Divide samples: Collect the same object several times, use one part of the data of each object for training, and the other part for verifying and testing.

3. Divide objects: Collect different objects under the same material several times, use the data of one part of the object for training, and the data of the other part for verifying and testing.

**Comment by hailanshanbhag** [comment]
Hello, 

Just to clarify, both train and test sets contain the same set of objects, however the environments and setup the experiments were done in differed. So I'm not sure the questions you've asked pertain to this kind of set up. 

1. Frames were not divided. So if a frame was collected during a certain experiment for a certain object, it was only used in training or only used in testing.
2. Samples were also not divided in the sense if we ran an experiment in one setup on an object multiple times, it was not used in both the train and test set. 
3. All objects are used in test and train sets. 

However, you are welcome to split the dataset as you wish by changing parameters on things such as the objects we are testing/training on since you have access to all the processed data.

I hope this answers your questions.

**Comment by zjy6Archer** [comment]
Thank you for your answer,
I've seen the results of your experiments in different environment Settings.
I have another question about the fact that, in 7 material categories classification experiments,  there are multiple different objects in each of the 7 material categories, and you have used data from one environment setting for training and data from another environment setting for testing. 
Have you ever tried to use one part of objects int each class to train and the other part to test, so as to verify the model's ability to recognize materials of unseen objects? (For example, in the metal class, choose aluminum, USRP cover and copper for training, and choose steel, metal box and metal pot for testing.) If the model still has a good recognition ability in this case, it can also show that the model can perform a good material recognition on any unseen object. That's what I mean by dividing objects.

**Comment by hailanshanbhag** [comment]
Yes, we have done that, and you can see the paper for some of those results.
